### ISSUE TITLE
Supporting new versions of AGP

### ISSUE THREAD

**Issue by eygraber** [gradle/android-cache-fix-gradle-plugin#216]
Is there a timeline for when new versions of AGP will be supported? I really like the idea of this plugin, but if it will be an impediment to keeping up to date with AGP I would have to drop it.

**Comment by TWiStErRob** [comment]
I have the same feeling when seeing the warning mentioned in https://github.com/gradle/android-cache-fix-gradle-plugin/issues/215. I'm thinking how safe it can be based on the level (genius) of internal workarounds.

Based on previous minor update (7.0.2 -> 7.0.3):
October 11 https://androidstudio.googleblog.com/2021/10/android-studio-arctic-fox-202031-patch.html
November 12 https://github.com/gradle/android-cache-fix-gradle-plugin/releases/tag/2.4.5

https://github.com/gradle/android-cache-fix-gradle-plugin/issues/215 will take a bit of time.

@eygraber out of curiosity which versions are you worried about?
And is your feedback because of the warning mentioned in https://github.com/gradle/android-cache-fix-gradle-plugin/issues/215?

**Comment by eygraber** [comment]
Yes, my feedback is because of the warning. However, I thought it would be a warning that would fail my build (`allWarningsAsErrors = true`), but it doesn't.

I'm also worried about incompatibilities (especially silent ones), although it doesn't seem like I've run into any issues using the plugin with AGP 7.2.0-alpha06.

**Comment by TWiStErRob** [comment]
allWarningsAsErrors is in the DSL for configuring Kotlin compilation. It only affects Kotlin. This one is a warning [written to Gradle's logger](https://github.com/gradle/android-cache-fix-gradle-plugin/blob/b8cc54d0696955b9b82b0b14c8944eb4a8fde31f/src/main/groovy/org/gradle/android/Warnings.groovy#L20) as a warning and therefore it won't affect builds.

**Comment by ghale** [comment]
We try to keep up with new versions when they come out, but generally there's a lag between when a new version of AGP is made available and when we 1) notice it, 2) test against it and 3) fix any new issues that may have been introduced.  In general, minor revisions don't introduce new problems, but alpha and beta releases typically introduce a number of changes that affect these workarounds and can delay getting a compatible version out.  We do _try_ to be timely, but other priorities can sometimes interfere.

I think it would be unlikely that you would have any silent issues related to version incompatibilities and build correctness.  The most likely case is an error that causes a build failure, in which case, the untested-version warning is intended to clue you in to where the issue might lie.  In the vast majority of the cases, if your build still executes, it should be safe and the only negative side effect is the warning itself (i.e. we just haven't tested it and rubber stamped the compatibility yet).  However, insert standard disclaimer here that this is just a bunch of bits in a box and it may or may not do something useful - use at your own risk.

The long term hope, at least, is that all of the associated issues will be fixed in AGP and this plugin will simply be obsoleted.  There is clear progress in this direction (i.e. the plugin does less and less for later versions of AGP), but as of now, this plugin is still necessary to patch the last mile.

**Comment by eygraber** [comment]
I've tried adding `org.gradle.android.cache-fix.ignoreVersionCheck=true` to my `gradle.properties` but I'm still seeing the warning.

**Comment by runningcode** [comment]
Please adjust it to `systemProp.org.gradle.android.cache-fix.ignoreVersionCheck=true` and let us know if it is still happening.

**Comment by vanniktech** [comment]
Would it be possible to include `systemProp.org.gradle.android.cache-fix.ignoreVersionCheck=true` in the [message](https://github.com/gradle/android-cache-fix-gradle-plugin/blob/67b2365309d671b8d2198e65ea84637f2d364a33/src/main/groovy/org/gradle/android/Warnings.groovy#L11)? I've tried without the `systemProp.` prefix in my gradle.properties and was confused as it didn't work.

**Comment by TWiStErRob** [comment]
@vanniktech I think they would accept that PR, requesting `-D` is a bit strange, it doesn't really work in a shared environment.
