### ISSUE TITLE
`RoomSchemaLocationWorkaround` doesn't declare outputs

### ISSUE THREAD

**Issue by BraisGabin** [gradle/android-cache-fix-gradle-plugin#336]
I'm seeing this on my scans:

Path | :my-module:mergeRoomSchemaLocations
-- | --
Type | org.gradle.android.workarounds.RoomSchemaLocationWorkaround$RoomSchemaLocationMergeTask

The task was not up-to-date because it did not have any declared outputs.

---

on the `build.gradle.kts` of `:my-module` I have this (exactly the same from the README.md):

```kotlin
room {
    schemaLocationDir.set(file("schemas"))
}
```

And it works bacause if I change the value to `file("asdf")` the output is generated in that new directory.

Gradle: 7.5
AGP: 7.2.1
Room: 2.2.6 (using kapt)

**Comment by ghale** [comment]
This task is [not incremental by design](https://github.com/gradle/android-cache-fix-gradle-plugin/blob/0af648712bf0f960325f590c13fd090b804cc218/src/main/groovy/org/gradle/android/workarounds/RoomSchemaLocationWorkaround.groovy#L379-L386).  Basically, we originally wrote this to work _exactly_ like it does when you don't use the workaround (i.e. when you just set the annotation processor argument) as flawed as that might be.  We _could_ make this incremental, but there are some funny edge cases where it wouldn't do exactly the same thing.  Since the task should be really fast (i.e. it's only copying a few xml files) making it non-incremental was a safe way to ensure identical behavior.

Having said that, I'm not sure it _needs_ to do exactly the same thing as when you don't use the workaround.  This was just the conservative approach we took when we initially created this workaround (i.e. we wanted there to be no difference in behavior between using the workaround or not).  If you're seeing that executing this task is actually expensive, I could be convinced to make this incremental.

**Comment by BraisGabin** [comment]
It's not expensive: 0.005s. 

If that task should not be UP-TO-DATE for the sake of correctness I'm fine with it.

> Having said that, I'm not sure it _needs_ to do exactly the same thing as when you don't use the workaround.

I think that looking at the Google implementation of this feature they don't care too much about the exactly behaviour. They just want to generate that file. So, maybe, it's not worth it to keep exactly the same bahaviour.

**Comment by ghale** [comment]
Ok, I'm inclined to leave it as is for the time being.  If we find an obvious advantage to changing it, then I'm open to doing so, but for now, I think I'd rather just leave it.
