### ISSUE TITLE
RoomSchemaLocationMergeTask is updating all schemas' last modified timestamp

### ISSUE THREAD

**Issue by mcumings** [gradle/android-cache-fix-gradle-plugin#339]
When attempting to define a custom task that uses the schema directory as an input (via `@InputDirectory`) I noticed that the input was being invalidated when the schemas had not changed.  Investigating further I noticed that the timestamps were changing on every build as a result of the workaround being applied.

Please update the workaround to only copy files back into the origin directory if the contents have changed (or some similarly functional strategy) to prevent cache invalidation for downstream consumers of this directory.

**Comment by ghale** [comment]
I'm sure the copy is causing the last modified timestamp to change, but I don't think that this (in and of itself) would cause downstream task inputs to be invalidated.  The fingerprints of the inputs are based on the _content_ of the files, so if the content was the same, it should hash to the same fingerprint and downstream tasks should still be up-to-date or get cache hits as expected.  I suspect that there may be some actual differences in the content that's causing downstream tasks to miss on up-to-date and cache checks.

One detail to this is that there is an optimization in the fingerprinting such that it won't try to fingerprint a file whose timestamp has not changed since the last time it was fingerprinted.  So if the timestamp is changing, it could be causing extra fingerprinting to take place (for these files only), but again, as long as the content is the same, it should still calculate the same fingerprint.

Running a quick test of this showed downstream tasks always getting up-to-date or cache hits even though the merge task executed.  The downstream tasks only executed when the schema files actually changed.

Of course, that's how everything is _supposed_ to work.  It's always possible there's a defect somewhere.  If you still feel like this is throwing off the inputs of downstream tasks when the schemas are identical, please share some build scans with me via DM and I'll take a look.

**Comment by mcumings** [comment]
Thanks, Gary.  I believe I was using `git status` to verify lack of file change so perhaps it is a line ending delta or something similar.  I'll spin this back up and take another look and will let you know.

**Comment by mcumings** [comment]
Well, I went back to this and can no longer get it to manifest.  If I ever see it again I'll see if I can narrow down further.  Until then, closing!

thanks!
