### ISSUE TITLE
MergeSourceSetFoldersWorkaround still valid (won't be fixed by Google)?

### ISSUE THREAD

**Issue by G00fY2** [gradle/android-cache-fix-gradle-plugin#607]
MergeSourceSetFoldersWorkaround has an empty `fixedIn` parameter. But actually the status in the linked issue is set:

> Status: Won't Fix (Intended Behavior)
We tried to add @DoNotCacheByDefault but got performance regression from some of our benchmarks so we revert the change in I031cf4a63f8c45538cc5247d29e2d30d03cfe21e

Does it make sense to then still ship this workaround?

If Gradle teams still thinks this is required I would expect a new issue with some data to hold against their result.

**Comment by runningcode** [comment]
Thanks for bringing this up.

The underlying issue was that the `MergeSourceSetFolders` task launches too many worker actions. See this comment for more details: https://github.com/gradle/android-cache-fix-gradle-plugin/issues/225#issuecomment-1018848201 

We filed this bug to address it: https://issuetracker.google.com/issues/215395137

The disabling of caching was just a temporary workaround. It makes sense to remove the workaround. We need to figure out in which version it would make sense to start disabling it.

**Comment by ribafish** [comment]
This was fixed in AGP `8.4.0-alpha01` and the workaround removed in [this PR](https://github.com/gradle/android-cache-fix-gradle-plugin/pull/635)
